# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Mod Versions
mod_version = 1.3.2
minecraft_version = 1.21.1
neo_version = 21.1.128

# build dependency versions
mixin_version = 0.8.6
mixinextras_version = 0.4.1

#read more on this at https://github.com/neoforged/NeoGradle/blob/NG_7.0/README.md#apply-parchment-mappings
# you can also find the latest versions at: https://parchmentmc.org/docs/getting-started
neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17

# Dependency Versions
create_minecraft_version = 1.21.1
create_version = 6.0.3
# See https://maven.createmod.net/com/simibubi/create/create-1.21.1/ for a list of build numbers
create_version_number = 48
flywheel_minecraft_version = 1.21.1
flywheel_version = 1.0.1
registrate_version = MC1.21-1.3.0+62
jei_minecraft_version = 1.21.1
jei_version = 19.21.0.247
curios_minecraft_version = 1.21.1
curios_version = 9.2.2
ponder_version = 1.0.45
