# Gradle
org.gradle.jvmargs = -Xmx4G
org.gradle.daemon = false
org.gradle.parallel = true
org.gradle.caching = true
org.gradle.configuration-cache = true

# Minecraft / Forge
parchment_minecraft_version = 1.20.1
parchment_mappings_version = 2023.09.03
minecraft_version = 1.20.1
minecraft_version_range = [1.20.1, 1.21)
# 1.20.1: Neo is based on this version. Try not to bump
forge_version = 47.1.33
forge_version_range = [47.1.0, 48)
loader_version_range = [47,)

# Mod
mod_id = create_enchantment_industry
mod_artifact_id = create-enchantment-industry
mod_name = Create: Enchantment Industry
mod_license = LGPL-3.0-or-later
mod_version = 2.5.1b
mod_group_id = plus.dragons.createenchantmentindustry
mod_authors = DragonsPlus
mod_description = Enchantment, Experience, Enhancement and Enlightening - with Create
mod_github = https://github.com/DragonsPlusMinecraft/CreateEnchantmentIndustry

# Core dependencies
conditional_mixin_version = 0.6.4
mixin_version = 0.8.5
create_version = 6.0.8
create_version_number = 291
create_version_production = 6.0.8-291
create_version_range = [6.0.8, 6.1.0)
flywheel_version = 1.0.6-beta-266
registrate_version = MC1.20-1.3.3
ponder_version = 1.0.91
create_dragons_plus_version = 1.11.5
create_dragons_plus_version_range = [1.11.5, 1.12.0)
jei_version = 15.20.0.106
curios_version = 5.3.1

# Apotheosis 1.20.1
placebo_version = 8.6.2
apothic_attributes_version = 1.3.5
apotheosis_version = 7.4.8
apotheosis_version_range = [7.4.8, 8.0.0)
patchouli_version = 81-FORGE

# Touhou Little Maid 1.20.1-1.5.3
tlm_file_id = 8061847
tlm_version_range = [1.5.3, 1.6.0)
