# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Mod Versions
mod_version = 1.3.3
artifact_minecraft_version = 1.20.1
minecraft_version = 1.20.1
forge_version = 47.2.6

# build dependency versions
mixin_version = 0.8.5
parchment_version = 2023.09.03

# Dependency Versions
create_minecraft_version = 1.20.1
create_version = 6.0.6
create_version_number = 205
flywheel_minecraft_version = 1.20.1
flywheel_version = 1.0.4-243
registrate_version = MC1.20-1.3.3
jei_minecraft_version = 1.20.1
jei_version = 15.19.0.85
curios_minecraft_version = 1.20.1
curios_version = 5.3.1
ponder_version = 1.0.81
