name: Bug Report
description: Create a bug report to help us improve this mod
labels: [ "bug", "triage" ]
body:
  -   type: dropdown
      attributes:
        label: Minecraft Version
        description: The version of Minecraft you were using when the bug occured
        options:
          - "1.19.2"
          - "1.18.2"
      validations:
        required: true
  -   type: textarea
      attributes:
        label: Describe the Bug
        description: A clear and concise description of what the bug is
      validations:
        required: true
  -   type: textarea
      attributes:
        label: Reproduction Steps
        description: Tell us about the steps to reproduce the bug.
        value: |
          1.
          2.
          3.
          ...
      validations:
        required: true
  -   type: textarea
      attributes:
        label: Expected Result
        description: A clear and concise description of what you expected to happen
      validations:
        required: true
  -   type: textarea
      attributes:
        label: Screenshots and Videos
        description: If applicable, add screenshots or videos to help explain your problem.
      validations:
        required: false
  -   type: input
      attributes:
        label: Crash Report or Log
        description: If applicable, please add a **link** to the crash report or log that was created when this issue occured. You can upload the crash report to a site like Pastebin or GitHub Gist. Please **do not** paste the whole crash report in this issue.
      validations:
        required: false
  -   type: textarea
      attributes:
        label: Other Mods
        description: Please list any other mods that were running when the crash happened.
      validations:
        required: false
  -   type: markdown
      attributes:
        value: "If you are not using latest version of our mod, or not using recommended version of forge, please fill form below."
  -   type: input
      attributes:
        label: Mod Version
        description: The version of the mod you were using when the incompatibility occurred
        placeholder: x.y.z
      validations:
        required: true
  -   type: input
      attributes:
        label: Forge Version
        description: The version of Forge you were using when the bug incompatibility occurred
        placeholder: x.y.z
      validations:
        required: false
  -   type: markdown
      attributes:
        value: "Thank you for taking the time to make this bug report and help improve this mod!"