@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package plus.dragons.createenchantmentindustry.content.contraptions.fluids.ink;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;