@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package plus.dragons.createenchantmentindustry.content.contraptions.enchanting.copier;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;