@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package plus.dragons.createenchantmentindustry.content.contraptions.enchanting;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;